[package]
name = "rustcycles"
version = "0.0.0"
edition = "2021"
rust-version = "1.56"
resolver = "2"
authors = ["Martin Taibr <taibr.martin@gmail.com>"]

[profile.dev]
# Abort on panic might be a better default:
# https://vorner.github.io/2018/07/22/dont_panic.html
# This makes backtraces useless, see config-example.toml for a fix.
panic = "abort"

[profile.dev.package."*"]
# Optimize deps but not this crate itself (tip from macroquad).
# This seems to slightly improve performance (e.g. loading a model goes from 1.4 s to 0.2 s)
# and shouldn't meaningfully increase incremental compile times because deps only change rarely.
opt-level = 3

[profile.release]
panic = "abort"

[dependencies]
bincode = "1.3.3"
rg3d = "0.24.0"
#rg3d = { git = "https://github.com/rg3dengine/rg3d", rev = "8964b57f8f612ca4295bfaf677febee0c1e9eed8" }
#rg3d = { path = "../rg3d" }
serde = "1.0.130"
structopt = "0.3.25"
strum = "0.23.0"
strum_macros = "0.23.1"
