[package]
name = "rustcycles"
version = "0.0.0"
edition = "2018"
resolver = "2"
authors = ["Martin Taibr <taibr.martin@gmail.com>"]

[profile.dev]
# Abort on panic might be a better default:
# https://vorner.github.io/2018/07/22/dont_panic.html
panic = "abort"

[profile.dev.package."*"]
# Optimize deps but not this crate itself (tip from macroquad).
# This seems to slightly improve performance (e.g. loading a model goes from 1.4 s to 0.2 s)
# and shouldn't meaningfully increase incremental compile times because deps only change rarely.
opt-level = 3

[profile.release]
panic = "abort"

[dependencies]
rg3d = "0.23.0"
structopt = "0.3.25"
strum = "0.22"
strum_macros = "0.22"
