[package]
name = "rustcycles"
version = "0.0.0"
edition = "2021"
rust-version = "1.56"
resolver = "2"
authors = ["Martin Taibr <taibr.martin@gmail.com>"]

[profile.dev]
# Abort on panic might be a better default:
# https://vorner.github.io/2018/07/22/dont_panic.html
# This makes backtraces useless, see .cargo/config-example.toml for a fix.
panic = "abort"
opt-level = 1 # Can be changed without recompiling all deps

[profile.dev.package."*"]
# Optimize deps but not this crate itself (tip from macroquad).
# This seems to slightly improve performance (e.g. loading a model goes from 1.4 s to 0.2 s)
# and shouldn't meaningfully increase incremental compile times because deps only change rarely.
opt-level = 3
codegen-units = 1
debug = false

[profile.release]
panic = "abort"

# https://doc.rust-lang.org/cargo/reference/profiles.html#build-dependencies
# The reference might be wrong - it says this affects proc macros but in my experience it doesn't.
# No effect so far because we don't use and build deps yet.
[profile.dev.build-override]
opt-level = 3
codegen-units = 1

[profile.release.build-override]
opt-level = 3
codegen-units = 1

[features]
cli = ["structopt"]

[dependencies]
bincode = "1.3.3"
cvars = "0.1.0"
cvars-console = { path = "../cvars/cvars-console" }
fxhash = "0.2.1"
#fyrox = "0.27.1"
fyrox = { git = "https://github.com/FyroxEngine/Fyrox", rev = "d137bd39ea5d6171f6908e8f0a005bce4c2c90de" }
#fyrox = { git = "https://github.com/martin-t/Fyrox", rev = "922b623a929a079694adce1ded4006ef7d43fd02" }
#fyrox = { path = "../fyrox" }
inline_tweak = "1.0.8"
serde = { version = "1.0.144", features = ["derive"] }
structopt = { version = "0.3.25", optional = true }
strum = "0.24.0"
strum_macros = "0.24.3"
