
name: audit

# This is a separate file so it can have a separate badge in readme
# and therefore spread awareness of cargo audit a tiny bit.

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Runs at 15:00 UTC on Fri
    - cron: "0 15 * * 5"

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          version: latest
      - run: rustup update
      - run: cargo audit --version
      # RUSTSEC-2020-0016: net2 is unmaintained - fixed in notify 5.0 prerelease, waiting for release
      # RUSTSEC-2020-0056: stdweb is unmaintained - should be safe to ignore until stdweb is removed from instant
      # RUSTSEC-2020-0097: xcb - Soundness issue with base::Error
      # RUSTSEC-2021-0019: xcb - Multiple soundness issues
      # RUSTSEC-2021-0119: nix - Out-of-bounds write in nix::unistd::getgrouplist - waiting for new winit release
      # For more info: https://github.com/FyroxEngine/Fyrox/issues/208
      - run: cargo audit --deny warnings --ignore RUSTSEC-2020-0016 --ignore RUSTSEC-2020-0056 --ignore RUSTSEC-2020-0097 --ignore RUSTSEC-2021-0019 --ignore RUSTSEC-2021-0119
